# Generated by Django 6.0 on 2025-12-10 12:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name used as identifier in code and fixtures.', max_length=254, unique=True)),
                ('friendly_name', models.CharField(blank=True, help_text='Human readable name shown in the UI.', max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, db_index=True, help_text='Stock keeping unit or external product identifier.', max_length=254, null=True)),
                ('name', models.CharField(db_index=True, help_text='Product name shown in the catalog.', max_length=254)),
                ('description', models.TextField(help_text='Detailed description of the product.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in EUR.', max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='Average customer rating, from 0.0 to 5.0.', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('image_url', models.URLField(blank=True, help_text='Legacy external image URL, kept for backward compatibility.', max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, help_text='Locally stored product image.', null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True, help_text='If false, the product will be hidden from the catalog.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the product was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of the last update.')),
                ('category', models.ForeignKey(blank=True, help_text='Category this product belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'), models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx')],
            },
        ),
    ]
