# Generated by Django 6.0 on 2025-12-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options_remove_product_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_sku_ca0cdc_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_acti_ca4d9a_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
    ]
